#!/usr/bin/env python
# -*- coding: utf-8 -*-
subjects = (u'cliente',
            u'Product Owner',
            u'Scrum Master',
            u'Developer',
            u'Tester',
            u'QA Manager',
            u'consultor',
		u'señor con bigote',
		u'multimillonario derrochador',
		u'amante de git',
            u'camarero',
            u'superhéroe mierder',
            u'tu madre',
            u'tu padre',
            u'El vecino',
		u'desconocido',
		u'sombrerero loco',
		u'primo de un colega')
